// File automatically generated by swift-bridge.
#include <stdint.h>
typedef struct SoftSkia SoftSkia;
void __swift_bridge__$SoftSkia$_free(void* self);

void* __swift_bridge__$Vec_SoftSkia$new(void);
void __swift_bridge__$Vec_SoftSkia$drop(void* vec_ptr);
void __swift_bridge__$Vec_SoftSkia$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_SoftSkia$pop(void* vec_ptr);
void* __swift_bridge__$Vec_SoftSkia$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_SoftSkia$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_SoftSkia$len(void* vec_ptr);
void* __swift_bridge__$Vec_SoftSkia$as_ptr(void* vec_ptr);

void* __swift_bridge__$SoftSkia$new(void);
void __swift_bridge__$SoftSkia$create(void* self, uintptr_t id);
void __swift_bridge__$SoftSkia$set_attr(void* self, uintptr_t id, uint32_t x, uint32_t y, uint32_t width, uint32_t height, uint32_t r, uint32_t g, uint32_t b, void* shape, void* color, void* style);
void* __swift_bridge__$SoftSkia$to_base64(void* self);
void* __swift_bridge__$hello_rust(void);
void* __swift_bridge__$hello_soft_skia(void);


